// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bgpmspqezeuxsmgtuiex.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJncG1zcHFlemV1eHNtZ3R1aWV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyNzgzNzgsImV4cCI6MjA1Nzg1NDM3OH0.2y3UBp2j9oWoz3GoSY_3V0mO5sdUKgpDim0FzsNuad8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);